"""Canonical internal representation used by every stage of the pipeline.

Traceability contract (enforced by tests):

    Answer -> Citation -> SearchResult -> Chunk -> ContentBlock -> Page -> Document

Every object in that chain carries stable identifiers, so a citation rendered in
the UI can always be resolved back to the exact source region of the original
upload.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, Iterable, List, Optional, Sequence

from pydantic import BaseModel, ConfigDict, Field, field_validator


# --------------------------------------------------------------------------- #
# Enumerations
# --------------------------------------------------------------------------- #
class StrEnum(str, Enum):
    """`str`-backed enum so values serialise transparently to JSON/payloads."""

    def __str__(self) -> str:  # pragma: no cover - trivial
        return str(self.value)


class FileType(StrEnum):
    """Supported (and planned) input container formats."""

    PDF = "pdf"
    DOCX = "docx"
    PPTX = "pptx"
    TXT = "txt"
    MARKDOWN = "md"
    IMAGE = "image"
    XLSX = "xlsx"
    HTML = "html"
    UNKNOWN = "unknown"


class BlockType(StrEnum):
    """Semantic type of a :class:`ContentBlock`."""

    TEXT = "text"
    HEADING = "heading"
    OCR_TEXT = "ocr_text"
    HANDWRITING = "handwriting"
    IMAGE = "image"
    TABLE = "table"
    CHART = "chart"
    DIAGRAM = "diagram"
    CAPTION = "caption"
    SPEAKER_NOTES = "speaker_notes"
    PAGE_SNAPSHOT = "page_snapshot"

    @property
    def is_visual(self) -> bool:
        """True when the block carries an original visual worth sending to a VLM."""
        return self in _VISUAL_BLOCKS

    @property
    def is_textual(self) -> bool:
        return self in _TEXTUAL_BLOCKS


_VISUAL_BLOCKS = frozenset(
    {
        BlockType.IMAGE,
        BlockType.CHART,
        BlockType.DIAGRAM,
        BlockType.HANDWRITING,
        BlockType.PAGE_SNAPSHOT,
    }
)

_TEXTUAL_BLOCKS = frozenset(
    {
        BlockType.TEXT,
        BlockType.HEADING,
        BlockType.OCR_TEXT,
        BlockType.CAPTION,
        BlockType.SPEAKER_NOTES,
        BlockType.TABLE,
    }
)


class SourceKind(StrEnum):
    """How the text of a block was obtained. Drives trust/confidence display."""

    DIGITAL = "digital"          # selectable text extracted losslessly
    OCR = "ocr"                  # optical character recognition
    VISION = "vision"            # generated by a vision model (description)
    STRUCTURED = "structured"    # parsed structure, e.g. a DOCX/PPTX table
    DERIVED = "derived"          # normalised/summarised from another block


class IngestionStatus(StrEnum):
    """Lifecycle of a document inside a session."""

    PENDING = "pending"
    PARSING = "parsing"
    ANALYZING = "analyzing"
    CHUNKING = "chunking"
    EMBEDDING = "embedding"
    INDEXING = "indexing"
    READY = "ready"
    FAILED = "failed"
    DUPLICATE = "duplicate"


class PipelineStage(StrEnum):
    """User-facing progress stages surfaced by the UI."""

    UPLOADING = "Uploading"
    PARSING = "Parsing"
    EXTRACTING_TEXT = "Extracting text"
    ANALYZING_VISUALS = "Analyzing visuals"
    CHUNKING = "Generating chunks"
    EMBEDDING = "Creating embeddings"
    INDEXING = "Indexing"
    READY = "Ready"


class Language(StrEnum):
    """Coarse language buckets used for filtering and prompt steering."""

    ARABIC = "ar"
    ENGLISH = "en"
    MIXED = "mixed"
    UNKNOWN = "unknown"


class Role(StrEnum):
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class RetrievalStrategy(StrEnum):
    VECTOR = "vector"
    KEYWORD = "keyword"
    HYBRID = "hybrid"


class QueryScope(StrEnum):
    """How broadly retrieval must cover the selected documents."""

    FOCUSED = "FOCUSED"
    GLOBAL = "GLOBAL"
    EXHAUSTIVE = "EXHAUSTIVE"
    MULTI_PART = "MULTI_PART"


# --------------------------------------------------------------------------- #
# Exceptions
# --------------------------------------------------------------------------- #
class OmniRAGError(Exception):
    """Base class for all OmniRAG errors."""

    default_user_message = "Something went wrong. Please try again."

    def __init__(self, detail: str = "", *, user_message: Optional[str] = None) -> None:
        super().__init__(detail or user_message or self.default_user_message)
        self.detail = detail
        self.user_message = user_message or self.default_user_message


class ConfigurationError(OmniRAGError):
    default_user_message = (
        "OmniRAG is not configured correctly. Check your API keys and settings."
    )


class MissingCredentialError(ConfigurationError):
    def __init__(self, variable: str, purpose: str = "") -> None:
        suffix = f" ({purpose})" if purpose else ""
        super().__init__(
            f"Missing required credential: {variable}{suffix}",
            user_message=(
                f"`{variable}` is not configured{suffix}. "
                "Add it to your environment or Streamlit secrets."
            ),
        )
        self.variable = variable


class IngestionError(OmniRAGError):
    default_user_message = "This document could not be processed."


class UnsupportedFileTypeError(IngestionError):
    def __init__(self, filename: str, extension: str, supported: str = "") -> None:
        super().__init__(
            f"Unsupported extension '{extension}' for file '{filename}'",
            user_message=(
                f"**{filename}** is not a supported file type."
                + (f" Supported types: {supported}." if supported else "")
            ),
        )


class FileTooLargeError(IngestionError):
    def __init__(self, filename: str, size_mb: float, limit_mb: float) -> None:
        super().__init__(
            f"'{filename}' is {size_mb:.1f} MB, limit is {limit_mb:.1f} MB",
            user_message=(
                f"**{filename}** is {size_mb:.1f} MB which exceeds the "
                f"{limit_mb:.0f} MB upload limit."
            ),
        )


class EmptyDocumentError(IngestionError):
    def __init__(self, filename: str) -> None:
        super().__init__(
            f"'{filename}' produced no extractable content",
            user_message=(
                f"No readable content was found in **{filename}**. "
                "If it is a scan, enable an OCR or vision provider."
            ),
        )


class CorruptedDocumentError(IngestionError):
    def __init__(self, filename: str, detail: str = "") -> None:
        super().__init__(
            f"'{filename}' could not be opened: {detail}",
            user_message=f"**{filename}** appears to be corrupted or password protected.",
        )


class ProviderError(OmniRAGError):
    """Base class for failures coming from an external provider."""

    default_user_message = "An external service failed. Please try again."

    def __init__(
        self,
        detail: str = "",
        *,
        user_message: Optional[str] = None,
        provider: str = "",
        retryable: bool = False,
    ) -> None:
        super().__init__(detail, user_message=user_message)
        self.provider = provider
        self.retryable = retryable


class ProviderUnavailableError(ProviderError):
    """Provider-side outage: 5xx, connection failure, model temporarily down."""

    default_user_message = "The selected AI provider is unavailable right now."

    def __init__(self, detail: str = "", *, user_message: Optional[str] = None,
                 provider: str = "", retryable: bool = True) -> None:
        super().__init__(detail, user_message=user_message, provider=provider, retryable=retryable)


class RateLimitError(ProviderError):
    """429 / quota exhaustion.

    ``quota_exhausted`` marks the *billing* kind (Gemini ``RESOURCE_EXHAUSTED``,
    OpenAI ``insufficient_quota``). Waiting will not help, so the retry policy
    skips backoff and the router switches provider immediately.
    """

    default_user_message = "Rate limit reached. Waiting before retrying."

    def __init__(
        self,
        detail: str = "",
        *,
        provider: str = "",
        retry_after: float | None = None,
        quota_exhausted: bool = False,
        quota_scope: str = "temporary",
        reset_at: str = "",
    ):
        super().__init__(detail, provider=provider, retryable=not quota_exhausted)
        self.retry_after = retry_after
        self.quota_exhausted = quota_exhausted
        self.quota_scope = quota_scope
        self.reset_at = reset_at


class ProviderAuthError(ProviderError):
    """401/403 — a bad or missing key. Never retried, never falls back."""

    default_user_message = "The AI provider rejected the configured API key."

    def __init__(self, detail: str = "", *, user_message: Optional[str] = None, provider: str = ""):
        super().__init__(detail, user_message=user_message, provider=provider, retryable=False)


class ProviderBadRequestError(ProviderError):
    """400/404/422 — our request or configuration is wrong. Not retryable."""

    default_user_message = "The request sent to the AI provider was rejected as invalid."

    def __init__(self, detail: str = "", *, user_message: Optional[str] = None, provider: str = ""):
        super().__init__(detail, user_message=user_message, provider=provider, retryable=False)


class ProviderTokenBudgetExceededError(ProviderError):
    """Provider-specific request/token ceiling rejected an otherwise valid call."""

    default_user_message = "The AI request exceeded the provider's current token limit."

    def __init__(
        self,
        detail: str = "",
        *,
        user_message: Optional[str] = None,
        provider: str = "",
    ) -> None:
        super().__init__(
            detail,
            user_message=user_message,
            provider=provider,
            retryable=False,
        )


class ProviderPaymentRequiredError(ProviderError):
    """402 — the selected provider route requires credits."""

    default_user_message = "The selected AI route requires provider credits."

    def __init__(self, detail: str = "", *, user_message: Optional[str] = None,
                 provider: str = "") -> None:
        super().__init__(detail, user_message=user_message, provider=provider, retryable=False)


class ProviderPolicyError(ProviderError):
    """The model refused on safety/policy grounds."""

    default_user_message = (
        "The model declined to answer this request on safety grounds."
    )

    def __init__(self, detail: str = "", *, user_message: Optional[str] = None,
                 provider: str = "", reason: str = "") -> None:
        super().__init__(detail, user_message=user_message, provider=provider, retryable=False)
        self.reason = reason


class ProviderCapabilityError(ProviderError):
    """The chosen model cannot do what the request needs (e.g. no image input)."""

    default_user_message = (
        "The configured model cannot process images, so visual evidence "
        "could not be analysed."
    )

    def __init__(self, detail: str = "", *, user_message: Optional[str] = None,
                 provider: str = "", capability: str = "") -> None:
        super().__init__(detail, user_message=user_message, provider=provider, retryable=False)
        self.capability = capability


class AllProvidersFailedError(ProviderError):
    """Every provider in the chain failed. Carries the per-provider reasons."""

    default_user_message = "All configured AI providers failed to respond."

    def __init__(self, failures: "list[tuple[str, BaseException]]" | None = None) -> None:
        self.failures = failures or []
        detail = "; ".join(
            f"{name}: {type(exc).__name__}: {exc}" for name, exc in self.failures
        )
        safe_failures = [
            f"{name}: {getattr(exc, 'user_message', '')}"
            for name, exc in self.failures
            if getattr(exc, "user_message", "")
        ]
        super().__init__(
            detail or "no providers attempted",
            user_message=(
                "All configured AI providers failed. " + " ".join(safe_failures)
                if safe_failures
                else self.default_user_message
            ),
            retryable=False,
        )


class ProviderTimeoutError(ProviderError):
    default_user_message = "The AI provider took too long to respond."

    def __init__(self, detail: str = "", *, provider: str = "") -> None:
        super().__init__(detail, provider=provider, retryable=True)


class LLMError(ProviderError):
    default_user_message = "The language model could not generate an answer."


class EmbeddingError(ProviderError):
    default_user_message = "Embeddings could not be created for this content."


class OCRError(ProviderError):
    default_user_message = "Text recognition failed for this page."


class VisionError(ProviderError):
    default_user_message = "Visual analysis failed for this element."


class RerankError(ProviderError):
    default_user_message = "Reranking failed; falling back to retrieval order."


class VectorStoreError(OmniRAGError):
    default_user_message = "The vector database is unavailable."


class SessionIsolationError(OmniRAGError):
    """Raised when an operation would cross session boundaries."""

    default_user_message = "A data-isolation check failed; the request was blocked."


class RetrievalError(OmniRAGError):
    default_user_message = "Search over your documents failed."


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def _uuid() -> str:
    return uuid.uuid4().hex


def _now() -> datetime:
    return datetime.now(timezone.utc)


# --------------------------------------------------------------------------- #
# Base Model
# --------------------------------------------------------------------------- #
class OmniModel(BaseModel):
    """Base model with shared configuration."""

    model_config = ConfigDict(extra="forbid", validate_assignment=False)


# --------------------------------------------------------------------------- #
# Geometry & visuals
# --------------------------------------------------------------------------- #
class BoundingBox(OmniModel):
    """Axis-aligned box in PDF/page point coordinates (origin top-left)."""

    x0: float
    y0: float
    x1: float
    y1: float

    @property
    def width(self) -> float:
        return max(0.0, self.x1 - self.x0)

    @property
    def height(self) -> float:
        return max(0.0, self.y1 - self.y0)

    @property
    def area(self) -> float:
        return self.width * self.height

    def as_tuple(self) -> tuple[float, float, float, float]:
        return (self.x0, self.y0, self.x1, self.y1)


class VisualRef(OmniModel):
    """Pointer to the original visual backing a block."""

    asset_id: str
    media_type: str = "image/png"
    width: Optional[int] = None
    height: Optional[int] = None
    origin: str = "embedded"  # embedded | page_render | crop | upload
    page_number: Optional[int] = None


class TableData(OmniModel):
    """A table kept in several representations at once."""

    rows: List[List[str]] = Field(default_factory=list)
    header: Optional[List[str]] = None
    markdown: str = ""
    summary: str = ""
    n_rows: int = 0
    n_cols: int = 0

    @classmethod
    def from_rows(
        cls, rows: Sequence[Sequence[Any]], *, has_header: bool = True
    ) -> "TableData":
        clean: List[List[str]] = [
            ["" if c is None else str(c).strip() for c in row] for row in rows
        ]
        clean = [r for r in clean if any(cell for cell in r)]
        header = clean[0] if (has_header and clean) else None
        body = clean[1:] if header is not None else clean
        n_cols = max((len(r) for r in clean), default=0)
        return cls(
            rows=body,
            header=header,
            markdown=_rows_to_markdown(header, body, n_cols),
            n_rows=len(body),
            n_cols=n_cols,
        )


def _rows_to_markdown(
    header: Optional[List[str]], body: List[List[str]], n_cols: int
) -> str:
    if n_cols == 0:
        return ""

    def pad(row: Sequence[str]) -> List[str]:
        cells = [str(c).replace("|", "\\|").replace("\n", " ").strip() for c in row]
        return cells + [""] * (n_cols - len(cells))

    head = pad(header) if header else [f"col_{i + 1}" for i in range(n_cols)]
    lines = ["| " + " | ".join(head) + " |", "| " + " | ".join(["---"] * n_cols) + " |"]
    lines.extend("| " + " | ".join(pad(r)) + " |" for r in body)
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Content
# --------------------------------------------------------------------------- #
class ContentBlock(OmniModel):
    """The atomic unit produced by ingestion."""

    block_id: str = Field(default_factory=_uuid)
    document_id: str
    session_id: str
    page_number: int = 1
    block_type: BlockType = BlockType.TEXT
    source_kind: SourceKind = SourceKind.DIGITAL

    text: str = ""
    visual_description: str = ""
    table: Optional[TableData] = None
    visual: Optional[VisualRef] = None
    bbox: Optional[BoundingBox] = None

    language: Language = Language.UNKNOWN
    confidence: Optional[float] = None
    uncertain: bool = False
    parent_section: Optional[str] = None
    order: int = 0
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @field_validator("confidence")
    @classmethod
    def _clamp_confidence(cls, v: Optional[float]) -> Optional[float]:
        if v is None:
            return None
        return max(0.0, min(1.0, float(v)))

    @property
    def search_text(self) -> str:
        """Text used for embedding / keyword search."""
        parts: List[str] = []
        if self.parent_section:
            parts.append(self.parent_section)
        if self.text.strip():
            parts.append(self.text.strip())
        if self.visual_description.strip():
            parts.append(self.visual_description.strip())
        if self.table is not None:
            if self.table.summary:
                parts.append(self.table.summary)
            if self.table.markdown:
                parts.append(self.table.markdown)
        return "\n\n".join(parts).strip()

    @property
    def has_visual(self) -> bool:
        return self.visual is not None

    @property
    def is_empty(self) -> bool:
        return not self.search_text


class Page(OmniModel):
    """A page (PDF), slide (PPTX), or logical section (DOCX/TXT)."""

    page_id: str = Field(default_factory=_uuid)
    document_id: str
    session_id: str
    page_number: int
    label: Optional[str] = None
    width: Optional[float] = None
    height: Optional[float] = None
    is_scanned: bool = False
    blocks: List[ContentBlock] = Field(default_factory=list)
    page_image: Optional[VisualRef] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @property
    def display_label(self) -> str:
        return self.label or f"Page {self.page_number}"

    @property
    def text(self) -> str:
        return "\n\n".join(b.search_text for b in self.blocks if b.search_text)


class Document(OmniModel):
    """A single uploaded file after parsing."""

    document_id: str = Field(default_factory=_uuid)
    session_id: str
    filename: str
    file_type: FileType = FileType.UNKNOWN
    content_hash: str = ""
    size_bytes: int = 0
    page_count: int = 0
    language: Language = Language.UNKNOWN
    status: IngestionStatus = IngestionStatus.PENDING
    created_at: datetime = Field(default_factory=_now)
    pages: List[Page] = Field(default_factory=list)
    source_asset_id: Optional[str] = None
    warnings: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @property
    def blocks(self) -> List[ContentBlock]:
        return [b for p in self.pages for b in p.blocks]

    @property
    def size_mb(self) -> float:
        return self.size_bytes / (1024 * 1024)

    def page(self, number: int) -> Optional[Page]:
        return next((p for p in self.pages if p.page_number == number), None)

    def block(self, block_id: str) -> Optional[ContentBlock]:
        return next((b for b in self.blocks if b.block_id == block_id), None)


class DocumentSummary(OmniModel):
    """Lightweight view of a document for the sidebar / library."""

    document_id: str
    session_id: str
    filename: str
    file_type: FileType
    size_bytes: int = 0
    page_count: int = 0
    chunk_count: int = 0
    block_count: int = 0
    visual_block_count: int = 0
    table_count: int = 0
    language: Language = Language.UNKNOWN
    status: IngestionStatus = IngestionStatus.PENDING
    content_hash: str = ""
    source_asset_id: Optional[str] = None
    error: Optional[str] = None
    warnings: List[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=_now)
    medical_metadata: Optional["MedicalMetadata"] = None

    @property
    def size_label(self) -> str:
        size = float(self.size_bytes)
        for unit in ("B", "KB", "MB", "GB"):
            if size < 1024 or unit == "GB":
                return f"{size:.0f} {unit}" if unit == "B" else f"{size:.1f} {unit}"
            size /= 1024
        return f"{size:.1f} GB"


# --------------------------------------------------------------------------- #
# Medical metadata
# --------------------------------------------------------------------------- #
class MedicalDocumentType(StrEnum):
    """Classification of the medical document."""
    CLINICAL_GUIDELINE = "clinical_guideline"
    RESEARCH_PAPER = "research_paper"
    SYSTEMATIC_REVIEW = "systematic_review"
    REPORT = "report"
    PROTOCOL = "protocol"
    TEXTBOOK = "textbook"
    PATIENT_INFO = "patient_info"
    REGULATORY = "regulatory"
    UNKNOWN = "unknown"


class MedicalDomain(StrEnum):
    """Broad medical domain the document belongs to."""
    INFECTIOUS_DISEASE = "infectious_disease"
    CARDIOLOGY = "cardiology"
    ONCOLOGY = "oncology"
    PEDIATRICS = "pediatrics"
    SURGERY = "surgery"
    PHARMACOLOGY = "pharmacology"
    EPIDEMIOLOGY = "epidemiology"
    PUBLIC_HEALTH = "public_health"
    EMERGENCY_MEDICINE = "emergency_medicine"
    INTERNAL_MEDICINE = "internal Medicine"
    OTHER = "other"
    UNKNOWN = "unknown"


class EvidenceLevel(StrEnum):
    """Evidence quality level of the document content."""
    GUIDELINE = "guideline"
    SYSTEMATIC_REVIEW = "systematic_review"
    META_ANALYSIS = "meta_analysis"
    RCT = "rct"
    OBSERVATIONAL = "observational"
    EXPERT_OPINION = "expert_opinion"
    UNKNOWN = "unknown"


class MedicalMetadata(OmniModel):
    """Structured medical metadata extracted from a document.

    Captures domain-specific information useful for retrieval filtering,
    display, and clinical context. All fields are optional — only
    what can be reliably extracted is populated.
    """

    document_type: MedicalDocumentType = MedicalDocumentType.UNKNOWN
    medical_domain: MedicalDomain = MedicalDomain.UNKNOWN
    evidence_level: EvidenceLevel = EvidenceLevel.UNKNOWN
    authoring_organization: str = ""
    publication_year: Optional[int] = None
    isbn: str = ""
    keywords: List[str] = Field(default_factory=list)
    target_audience: str = ""
    summary: str = ""

    def has_content(self) -> bool:
        """True if at least one meaningful field was populated."""
        return bool(
            self.document_type != MedicalDocumentType.UNKNOWN
            or self.medical_domain != MedicalDomain.UNKNOWN
            or self.authoring_organization
            or self.publication_year
            or self.keywords
            or self.summary
        )


# --------------------------------------------------------------------------- #
# Chunks & retrieval
# --------------------------------------------------------------------------- #
class Chunk(OmniModel):
    """A retrievable unit. Always traceable to its source blocks."""

    chunk_id: str = Field(default_factory=_uuid)
    document_id: str
    session_id: str
    filename: str
    file_type: FileType = FileType.UNKNOWN
    page_number: int = 1
    page_label: str = ""
    block_ids: List[str] = Field(default_factory=list)
    block_type: BlockType = BlockType.TEXT
    source_kind: SourceKind = SourceKind.DIGITAL
    text: str = ""
    section: Optional[str] = None
    language: Language = Language.UNKNOWN
    visual: Optional[VisualRef] = None
    confidence: Optional[float] = None
    uncertain: bool = False
    token_estimate: int = 0
    order: int = 0
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @field_validator("block_ids")
    @classmethod
    def _require_provenance(cls, v: List[str]) -> List[str]:
        if not v:
            raise ValueError("chunk must reference at least one source block_id")
        return v

    @property
    def citation_label(self) -> str:
        return f"[{self.filename} — {self.page_label or f'Page {self.page_number}'}]"

    def to_payload(self) -> Dict[str, Any]:
        """Flat payload stored next to the vector. Used for metadata filtering."""
        return {
            "chunk_id": self.chunk_id,
            "session_id": self.session_id,
            "document_id": self.document_id,
            "filename": self.filename,
            "file_type": str(self.file_type),
            "page_number": self.page_number,
            "page_label": self.page_label,
            "block_ids": list(self.block_ids),
            "block_type": str(self.block_type),
            "source_kind": str(self.source_kind),
            "language": str(self.language),
            "text": self.text,
            "section": self.section,
            "confidence": self.confidence,
            "uncertain": self.uncertain,
            "order": self.order,
            "token_estimate": self.token_estimate,
            "visual_asset_id": self.visual.asset_id if self.visual else None,
            "visual_media_type": self.visual.media_type if self.visual else None,
            "visual_origin": self.visual.origin if self.visual else None,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_payload(cls, payload: Dict[str, Any]) -> "Chunk":
        visual = None
        if payload.get("visual_asset_id"):
            visual = VisualRef(
                asset_id=payload["visual_asset_id"],
                media_type=payload.get("visual_media_type") or "image/png",
                origin=payload.get("visual_origin") or "embedded",
                page_number=payload.get("page_number"),
            )
        return cls(
            chunk_id=payload["chunk_id"],
            session_id=payload["session_id"],
            document_id=payload["document_id"],
            filename=payload.get("filename", ""),
            file_type=FileType(payload.get("file_type", "unknown")),
            page_number=int(payload.get("page_number", 1)),
            page_label=payload.get("page_label", ""),
            block_ids=list(payload.get("block_ids") or ["unknown"]),
            block_type=BlockType(payload.get("block_type", "text")),
            source_kind=SourceKind(payload.get("source_kind", "digital")),
            language=Language(payload.get("language", "unknown")),
            text=payload.get("text", ""),
            section=payload.get("section"),
            confidence=payload.get("confidence"),
            uncertain=bool(payload.get("uncertain", False)),
            order=int(payload.get("order", 0)),
            token_estimate=int(payload.get("token_estimate", 0)),
            visual=visual,
            metadata=dict(payload.get("metadata") or {}),
        )


class SearchResult(OmniModel):
    """A chunk with the scores that got it there."""

    chunk: Chunk
    score: float = 0.0
    vector_score: Optional[float] = None
    keyword_score: Optional[float] = None
    rerank_score: Optional[float] = None
    strategy: str = "vector"
    rank: int = 0

    @property
    def chunk_id(self) -> str:
        return self.chunk.chunk_id


class RetrievalResult(OmniModel):
    """Everything the retrieval pipeline produced for one query."""

    query: str
    normalized_query: str = ""
    expanded_queries: List[str] = Field(default_factory=list)
    language: Language = Language.UNKNOWN
    results: List[SearchResult] = Field(default_factory=list)
    strategy: str = "hybrid"
    reranked: bool = False
    timings_ms: Dict[str, float] = Field(default_factory=dict)
    notes: List[str] = Field(default_factory=list)
    query_scope: str = "FOCUSED"
    candidate_count: int = 0
    unique_pages: int = 0
    total_pages: int = 0
    structured_matches: int = 0
    completeness_pass: bool = False

    @property
    def chunks(self) -> List[Chunk]:
        return [r.chunk for r in self.results]

    @property
    def is_empty(self) -> bool:
        return not self.results


class Citation(OmniModel):
    """A source shown under an answer. Index is 1-based, matching ``[1]`` markers."""

    index: int
    chunk_id: str
    document_id: str
    filename: str
    page_number: int
    page_label: str = ""
    block_type: BlockType = BlockType.TEXT
    source_kind: SourceKind = SourceKind.DIGITAL
    snippet: str = ""
    score: float = 0.0
    visual_asset_id: Optional[str] = None
    visual_media_type: Optional[str] = None
    uncertain: bool = False
    confidence: Optional[float] = None

    @property
    def label(self) -> str:
        return f"[{self.filename} — {self.page_label or f'Page {self.page_number}'}]"


class ChatMessage(OmniModel):
    """One turn of the conversation."""

    message_id: str = Field(default_factory=_uuid)
    role: Role
    content: str
    created_at: datetime = Field(default_factory=_now)
    citations: List[Citation] = Field(default_factory=list)
    retrieval: Optional[RetrievalResult] = None
    used_documents: List[str] = Field(default_factory=list)
    error: Optional[str] = None
    debug: Dict[str, Any] = Field(default_factory=dict)
    reply_to_message_id: Optional[str] = None


class AnswerResult(OmniModel):
    """Output of the generation stage."""

    answer: str
    citations: List[Citation] = Field(default_factory=list)
    retrieval: Optional[RetrievalResult] = None
    insufficient_evidence: bool = False
    model: str = ""
    used_images: int = 0
    usage: Dict[str, Any] = Field(default_factory=dict)
    warnings: List[str] = Field(default_factory=list)
    finish_reason: str = ""
    continued: bool = False
    generation_id: str = ""
    generation_debug: Dict[str, Any] = Field(default_factory=dict)


class IngestionResult(OmniModel):
    """Outcome of ingesting a single uploaded file."""

    filename: str
    document_id: Optional[str] = None
    status: IngestionStatus = IngestionStatus.PENDING
    summary: Optional[DocumentSummary] = None
    chunk_count: int = 0
    page_count: int = 0
    duplicate_of: Optional[str] = None
    error: Optional[str] = None
    warnings: List[str] = Field(default_factory=list)
    duration_s: float = 0.0

    @property
    def ok(self) -> bool:
        return self.status in (IngestionStatus.READY, IngestionStatus.DUPLICATE)


class SessionInfo(OmniModel):
    """Namespace metadata for one anonymous Streamlit session."""

    session_id: str
    created_at: datetime = Field(default_factory=_now)
    last_active: datetime = Field(default_factory=_now)
    document_count: int = 0
    chunk_count: int = 0


def blocks_of(pages: Iterable[Page]) -> List[ContentBlock]:
    return [b for p in pages for b in p.blocks]
